@echo off
setlocal

set "PROJECT_DIR=%~dp0frontend"
set "ANDROID_DIR=%PROJECT_DIR%\android"
set "SDK_PATH="

if defined ANDROID_HOME if exist "%ANDROID_HOME%" set "SDK_PATH=%ANDROID_HOME%"
if not defined SDK_PATH if defined ANDROID_SDK_ROOT if exist "%ANDROID_SDK_ROOT%" set "SDK_PATH=%ANDROID_SDK_ROOT%"
if not defined SDK_PATH if exist "%LOCALAPPDATA%\Android\Sdk" set "SDK_PATH=%LOCALAPPDATA%\Android\Sdk"

if not defined SDK_PATH (
  echo Android SDK not found.
  echo Install Android Studio SDK tools, then set ANDROID_HOME or ANDROID_SDK_ROOT.
  echo Expected default path: %LOCALAPPDATA%\Android\Sdk
  pause
  exit /b 1
)

set "SDK_PATH_POSIX=%SDK_PATH:\=/%"
> "%ANDROID_DIR%\local.properties" (
  echo ## Auto-generated by build-android-apk.bat
  echo sdk.dir=%SDK_PATH_POSIX%
)

REM Gradle / Android Gradle Plugin 8.x: use JDK 17 or 21. JDK 22+ often fails with
REM "Unsupported class file major version" (e.g. 69 = Java 25). Prefer Temurin 21 LTS.
set "USER_JAVA_HOME=%JAVA_HOME%"
set "JAVA_HOME="

for /d %%J in ("%ProgramFiles%\Eclipse Adoptium\jdk-21*") do set "JAVA_HOME=%%~fJ"
if defined JAVA_HOME if exist "%JAVA_HOME%\bin\java.exe" goto java_ok

set "JAVA_HOME="
for /d %%J in ("%ProgramFiles%\Eclipse Adoptium\jdk-17*") do set "JAVA_HOME=%%~fJ"
if defined JAVA_HOME if exist "%JAVA_HOME%\bin\java.exe" goto java_ok

set "JAVA_HOME="
for /d %%J in ("%ProgramFiles%\Microsoft\jdk-21*") do set "JAVA_HOME=%%~fJ"
if defined JAVA_HOME if exist "%JAVA_HOME%\bin\java.exe" goto java_ok

set "JAVA_HOME="
for /d %%J in ("%ProgramFiles%\Microsoft\jdk-17*") do set "JAVA_HOME=%%~fJ"
if defined JAVA_HOME if exist "%JAVA_HOME%\bin\java.exe" goto java_ok

set "JAVA_HOME="
for /d %%J in ("%ProgramFiles%\Java\jdk-21*") do set "JAVA_HOME=%%~fJ"
if defined JAVA_HOME if exist "%JAVA_HOME%\bin\java.exe" goto java_ok

set "JAVA_HOME="
for /d %%J in ("%ProgramFiles%\Java\jdk-17*") do set "JAVA_HOME=%%~fJ"
if defined JAVA_HOME if exist "%JAVA_HOME%\bin\java.exe" goto java_ok

REM Fall back to JAVA_HOME from environment only if it is not JDK 22+ (path heuristic)
if defined USER_JAVA_HOME if exist "%USER_JAVA_HOME%\bin\java.exe" (
  echo %USER_JAVA_HOME% | findstr /i "jdk-22 jdk-23 jdk-24 jdk-25 jdk-26 jdk-27 jdk-28 jdk-29" >nul
  if errorlevel 1 (
    set "JAVA_HOME=%USER_JAVA_HOME%"
    goto java_ok
  )
  echo Skipping JAVA_HOME ^(JDK 22+ breaks Android Gradle 8 / class file major version^):
  echo   %USER_JAVA_HOME%
)

echo.
echo No JDK 17 or 21 found. Android APK builds need Eclipse Temurin 21 ^(or 17^) LTS.
echo JDK 25 causes: Unsupported class file major version 69
echo Install JDK 21: https://adoptium.net/temurin/releases/?version=21
echo You can keep JDK 25 installed; only JAVA_HOME ^(or this script^) must pick JDK 21 for Gradle.
echo.
pause
exit /b 1

:java_ok
echo Using JAVA_HOME=%JAVA_HOME%

REM Write org.gradle.java.home to the user-level gradle.properties (highest precedence, overrides
REM any auto-detected or stale value such as an empty/corrupted JDK 25 install).
REM Gradle properties files require forward slashes in paths.
set "JAVA_HOME_FWD=%JAVA_HOME:\=/%"
if not exist "%USERPROFILE%\.gradle" mkdir "%USERPROFILE%\.gradle"
> "%USERPROFILE%\.gradle\gradle.properties" (
  echo ## Auto-generated by build-android-apk.bat
  echo org.gradle.java.home=%JAVA_HOME_FWD%
)
echo Wrote org.gradle.java.home=%JAVA_HOME_FWD% to %%USERPROFILE%%\.gradle\gradle.properties

echo Building Capacitor Android APK...
cd /d "%PROJECT_DIR%"

echo Step 1: Building web assets and syncing to Android...
call npm run build:android
if errorlevel 1 goto :error

echo.
echo Step 2: Building APK with Gradle...
cd android
call gradlew.bat assembleDebug
set "GRADLE_RC=%ERRORLEVEL%"
cd ..
if not "%GRADLE_RC%"=="0" goto :error
if not exist "%ANDROID_DIR%\app\build\outputs\apk\debug\app-debug.apk" (
  echo Gradle finished but app-debug.apk was not created.
  goto :error
)

echo.
echo Done! APK: frontend\android\app\build\outputs\apk\debug\app-debug.apk
echo (Debug build is signed and installable. For Play Store, use assembleRelease and sign with your keystore.)
pause
exit /b 0

:error
echo Build failed!
pause
exit /b 1
