@echo off
setlocal EnableDelayedExpansion

set "PROJECT_DIR=%~dp0frontend"
set "ANDROID_DIR=%PROJECT_DIR%\android"
set "SDK_PATH="

REM ── Android SDK (Android Studio default) ──
if defined ANDROID_HOME if exist "%ANDROID_HOME%" set "SDK_PATH=%ANDROID_HOME%"
if not defined SDK_PATH if defined ANDROID_SDK_ROOT if exist "%ANDROID_SDK_ROOT%" set "SDK_PATH=%ANDROID_SDK_ROOT%"
if not defined SDK_PATH if exist "%LOCALAPPDATA%\Android\Sdk" set "SDK_PATH=%LOCALAPPDATA%\Android\Sdk"

if not defined SDK_PATH (
  echo Android SDK not found.
  echo Install Android Studio, then set ANDROID_HOME or use the default SDK at:
  echo   %LOCALAPPDATA%\Android\Sdk
  pause
  exit /b 1
)

set "PATH=%SDK_PATH%\platform-tools;%SDK_PATH%\emulator;%PATH%"
set "SDK_PATH_POSIX=%SDK_PATH:\=/%"
> "%ANDROID_DIR%\local.properties" (
  echo ## Auto-generated by run-android-emulator.bat
  echo sdk.dir=%SDK_PATH_POSIX%
)

REM ── JDK 17/21 for Gradle (same rules as build-android-apk.bat) ──
set "USER_JAVA_HOME=%JAVA_HOME%"
set "JAVA_HOME="

for /d %%J in ("%ProgramFiles%\Eclipse Adoptium\jdk-21*") do set "JAVA_HOME=%%~fJ"
if defined JAVA_HOME if exist "%JAVA_HOME%\bin\java.exe" goto java_ok

set "JAVA_HOME="
for /d %%J in ("%ProgramFiles%\Eclipse Adoptium\jdk-17*") do set "JAVA_HOME=%%~fJ"
if defined JAVA_HOME if exist "%JAVA_HOME%\bin\java.exe" goto java_ok

set "JAVA_HOME="
for /d %%J in ("%ProgramFiles%\Microsoft\jdk-21*") do set "JAVA_HOME=%%~fJ"
if defined JAVA_HOME if exist "%JAVA_HOME%\bin\java.exe" goto java_ok

set "JAVA_HOME="
for /d %%J in ("%ProgramFiles%\Microsoft\jdk-17*") do set "JAVA_HOME=%%~fJ"
if defined JAVA_HOME if exist "%JAVA_HOME%\bin\java.exe" goto java_ok

set "JAVA_HOME="
for /d %%J in ("%ProgramFiles%\Java\jdk-21*") do set "JAVA_HOME=%%~fJ"
if defined JAVA_HOME if exist "%JAVA_HOME%\bin\java.exe" goto java_ok

set "JAVA_HOME="
for /d %%J in ("%ProgramFiles%\Java\jdk-17*") do set "JAVA_HOME=%%~fJ"
if defined JAVA_HOME if exist "%JAVA_HOME%\bin\java.exe" goto java_ok

if defined USER_JAVA_HOME if exist "%USER_JAVA_HOME%\bin\java.exe" (
  echo %USER_JAVA_HOME% | findstr /i "jdk-22 jdk-23 jdk-24 jdk-25 jdk-26 jdk-27 jdk-28 jdk-29" >nul
  if errorlevel 1 (
    set "JAVA_HOME=%USER_JAVA_HOME%"
    goto java_ok
  )
)

echo No JDK 17 or 21 found. Install Temurin 21: https://adoptium.net/temurin/releases/?version=21
pause
exit /b 1

:java_ok
set "JAVA_HOME_FWD=%JAVA_HOME:\=/%"
if not exist "%USERPROFILE%\.gradle" mkdir "%USERPROFILE%\.gradle"
> "%USERPROFILE%\.gradle\gradle.properties" (
  echo ## Auto-generated by run-android-emulator.bat
  echo org.gradle.java.home=%JAVA_HOME_FWD%
)
echo Using JAVA_HOME=%JAVA_HOME%
echo SDK=%SDK_PATH%

REM ── Start Android Studio virtual device if none is online ──
set "DEVICE_READY=0"
for /f "skip=1 tokens=1,2" %%A in ('adb devices 2^>nul') do (
  if "%%B"=="device" (
    echo Found device: %%A
    set "DEVICE_READY=1"
    goto devices_done
  )
)

:devices_done
if "!DEVICE_READY!"=="0" (
  echo No emulator running. Starting a virtual device...
  set "AVD_NAME="
  for /f "usebackq delims=" %%A in (`"%SDK_PATH%\emulator\emulator.exe" -list-avds 2^>nul`) do (
    if not defined AVD_NAME set "AVD_NAME=%%A"
  )
  if not defined AVD_NAME (
    echo No AVD found. In Android Studio: Device Manager - Create Virtual Device.
    pause
    exit /b 1
  )
  echo Launching AVD: !AVD_NAME!
  start "Android Emulator" "%SDK_PATH%\emulator\emulator.exe" -avd "!AVD_NAME!"
  echo Waiting for emulator to boot ^(this can take 1-2 minutes^)...
  adb wait-for-device >nul 2>&1
  set /a BOOT_WAIT=0
  :wait_boot
  adb shell getprop sys.boot_completed 2>nul | findstr /x "1" >nul && goto boot_ok
  set /a BOOT_WAIT+=1
  if !BOOT_WAIT! GEQ 120 (
    echo Emulator did not finish booting in time.
    pause
    exit /b 1
  )
  timeout /t 2 /nobreak >nul
  goto wait_boot
  :boot_ok
  echo Emulator ready.
)

cd /d "%PROJECT_DIR%"

echo.
echo Step 1: Build web app and sync to Android...
call npm run build:android
if errorlevel 1 goto :error

echo.
echo Step 2: Install and launch on emulator...
call npx cap run android
if errorlevel 1 goto :error

echo.
echo Slide is running on the emulator.
pause
exit /b 0

:error
echo Run failed!
pause
exit /b 1
